### ISSUE TITLE
Rive animation is not working with the `ftd.ui list`

### ISSUE THREAD

**Issue by gargajit** [fastn-stack/fastn#1365]
Page breaks if I use the rive kernel component in a list.

**Objective:** 
I am creating a right sidebar and want to add a rive animation using the kernel component.
**Example:** 
![image](https://github.com/fastn-stack/fastn/assets/118595104/c7bed36b-6c22-49c8-b0d2-d6c35a48da33)

**Outcome:**
- Dark-mode switcher stops working
- If you are in dark mode, the page loads in the system mode, and you can not switch
- At the bottom of the page, some area with whitespace renders (shown in the below image)
![image](https://github.com/fastn-stack/fastn/assets/118595104/60f4085c-31e7-4eac-97af-07101ef188e4)

**Comment by Heulitig** [comment]
This issue has been fixed in release 0.3.71
PR: https://github.com/fastn-stack/fastn/pull/1371
