### ISSUE TITLE
Link is not working (navigating to wrong page), need to replace it 

### ISSUE THREAD

**Issue by apneduniya** [fastn-stack/fastn#1374]
![image](https://github.com/fastn-stack/fastn/assets/113763427/693b75e8-d690-430c-858f-a9f2157bcc22)

How to create clean URLs link is redirecting to https://fastn.com/clean-urls/ (which even doesn't exist) whereas the correct URL for it is https://fastn.com/clean-urls/-/build/

I wanna fix this by making a PR, hope you will assign this to me 😄 .

**Comment by Arpita-Jaiswal** [comment]
@apneduniya Please go ahead and create the PR.

**Comment by gargajit** [comment]
The PR https://github.com/fastn-stack/fastn.com/pull/460 is merged after review. 
Marking this issue as resolved.
