### ISSUE TITLE
http processor loses cookies

### ISSUE THREAD

**Issue by Arpita-Jaiswal** [fastn-stack/fastn#1538]
When we make a request using [http processor](https://fastn.com/http/), if the response included any cookie, we do not propagate it to the browser. 

## Expected Behavior

Since we do send all cookies to upstream, it makes sense that upstream can also create cookies.

## Current Behavior

Upstream cookies are lost.

## Possible Solution

Store the cookies from each processor call in the Config or some such global structure, and pass it along the response.

## Steps to Reproduce (for bugs)

Call a http processor that sets a cookie, see if cookie is found in browser. 

## Context

We are building slides project which is using django as backend. Django is setting a few cookies to keep track of things, and those cookies gets set if the request is directly forwarded to django via endpoint feature, but if django tries to set the cookie via http processors they are getting lost. 

## Your Environment

- `fastn` Version (I.e, output of `fastn -v`): 0.4.8
- Operating System: Mac
- Web Browser: Safari

**Comment by siddhantk232** [comment]
Correct me if I am wrong but I think the intended use of the `http` processor in fastn is to make REST calls right? Do we expect REST services to set cookies?

**Comment by amitu** [comment]
Yes. The whole REST services are not just HTTP crowd is misguided, the term REST is a wastage of humanities time. Everything is just HTTP. HTTP has cookies, headers, content negotiation, caching etc etc, and so does our http processor.
