### ISSUE TITLE
check for duplicate properties

### ISSUE THREAD

**Issue by Arpita-Jaiswal** [fastn-stack/fastn#181]
Currently, this is allowed

```ftd
-- ftd.column foo:
caption title:

--- ftd.text:
text: $title
text: $title
```

We need to throw error if the same header is defined again

**Comment by AviralVerma13** [comment]
My PR for the issue is **Final duplicate headers** https://github.com/FifthTry/ftd/pull/235

**Comment by ashutosh887** [comment]
Is this issue resolved @Arpita-Jaiswal @AviralVerma13

**Comment by amitu** [comment]
@ashutosh887, lets try this out as well. Some of these issues are old and may have been resolved. But not sure about this one.

**Comment by ashutosh887** [comment]
Please check and let me know @amitu
