### ISSUE TITLE
Properties in FTD 0.3 not yet supported

### ISSUE THREAD

**Issue by Arpita-Jaiswal** [fastn-stack/fastn#591]
We need to support the following properties in FTD 0.3:

- `move-up`
- `move-down`
- `move-left`
- `move-right` 
- `rotate`
- `scale`
- `shadow`
- `background-gradient`
- `background-parallax`
- `style`
- `slot`

**Comment by amitu** [comment]
Shadow is now supported: https://github.com/fastn-stack/fastn/commit/a91748d959e49595f60751a879d5312f6cf2d460#diff-2a9ec7380484a61c619ec837a6377caaf3195b42b0fa3c9f9bd1ed2cb5d2f935R18
